stages:
  - deploy

# ----------- DEPLOY Vercel -----------
deploy-vercel:
  stage: deploy
  image: node:22
  variables:
    TOKEN: $VERCEL_TOKEN

  script:

    - npm install --global vercel
    - vercel pull --yes --environment=production --token="$TOKEN"
    - vercel build --prod --token="$TOKEN"
    - vercel deploy --prebuilt --prod --token="$TOKEN"
